src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RecipeRepository::class)]
class Recipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(cascade: ['remove'], fetch: 'EAGER', inversedBy: 'recipes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $idUser = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $prep_time = null;

    #[ORM\Column(nullable: true)]
    private ?int $cook_time = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $thumbnail = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToMany(targetEntity: Ustensil::class, mappedBy: 'idRecipe', cascade: ["persist", "remove"], fetch: 'EAGER')]
    private Collection $ustensils;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: Instructions::class, cascade: ["persist", "remove"], fetch: 'EAGER')]
    private Collection $instructions;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: RecipeIngredient::class, cascade: ["persist", "remove"], fetch: 'EXTRA_LAZY')]
    private Collection $recipeIngredients;

    public function __construct()
    {
		$this->ustensils = new ArrayCollection();
		$this->instructions = new ArrayCollection();
		$this->recipeIngredients = new ArrayCollection();

		$this->setCreatedAt(DateTimeImmutable::createFromFormat('Y-m-d', date('Y-m-d')));
		$this->setUpdatedAt(DateTimeImmutable::createFromFormat('Y-m-d', date('Y-m-d')));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?User
    {
        return $this->idUser;
    }

    public function setIdUser(?User $idUser): static
    {
        $this->idUser = $idUser;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrepTime(): ?int
    {
        return $this->prep_time;
    }

    public function setPrepTime(int $prep_time): static
    {
        $this->prep_time = $prep_time;

        return $this;
    }

    public function getCookTime(): ?int
    {
        return $this->cook_time;
    }

    public function setCookTime(?int $cook_time): static
    {
        $this->cook_time = $cook_time;

        return $this;
    }

    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(?string $thumbnail): static
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Ustensil>
     */
    public function getUstensils(): Collection
    {
        return $this->ustensils;
    }

    public function addUstensil(Ustensil $ustensil): static
    {
        if (!$this->ustensils->contains($ustensil)) {
            $this->ustensils->add($ustensil);
        }

		$ustensil->addIdRecipe($this);

        return $this;
    }

    public function removeUstensil(Ustensil $ustensil): static
    {
        if ($this->ustensils->removeElement($ustensil)) {
            $ustensil->removeIdRecipe($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Instructions>
     */
    public function getInstructions(): Collection
    {
        return $this->instructions;
    }

    public function addInstruction(Instructions $instruction): static
    {
        if (!$this->instructions->contains($instruction)) {
            $this->instructions->add($instruction);
            $instruction->setRecipe($this);
        }

        return $this;
    }

    public function removeInstruction(Instructions $instruction): static
    {
        if ($this->instructions->removeElement($instruction)) {
            // set the owning side to null (unless already changed)
            if ($instruction->getRecipe() === $this) {
                $instruction->setRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RecipeIngredient>
     */
    public function getRecipeIngredients(): Collection
    {
        return $this->recipeIngredients;
    }

    public function addRecipeIngredient(RecipeIngredient $recipeIngredient): static
    {
        if (!$this->recipeIngredients->contains($recipeIngredient)) {
            $this->recipeIngredients->add($recipeIngredient);
            $recipeIngredient->setRecipe($this);
        }

        return $this;
    }

    public function removeRecipeIngredient(RecipeIngredient $recipeIngredient): static
    {
        if ($this->recipeIngredients->removeElement($recipeIngredient)) {
            // set the owning side to null (unless already changed)
            if ($recipeIngredient->getRecipe() === $this) {
                $recipeIngredient->setRecipe(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory;


use DateTimeImmutable;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

	#[ORM\Column]
   private ?bool $isVerified = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $deleted_at = null;

    #[ORM\OneToMany(mappedBy: 'idUser', targetEntity: Recipe::class, cascade: ['remove'], orphanRemoval: true)]
    private Collection $recipes;

    #[ORM\ManyToMany(targetEntity: Recipe::class)]
    private Collection $favoriteRecipes;

    public function __construct()
    {
        $this->recipes = new ArrayCollection();
        $this->favorites = new ArrayCollection();

		$this->setCreatedAt(DateTimeImmutable::createFromFormat('Y-m-d', date('Y-m-d')));
		$this->setUpdatedAt(DateTimeImmutable::createFromFormat('Y-m-d', date('Y-m-d')));
  		$this->favoriteRecipes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password, bool $isHashed = false): static
    {

		$finalPWD = $password;

		//Si le mot de passe n'est pas encore hashé (pour le panel Admin)
		if(!$isHashed)
		{
			$factory = new PasswordHasherFactory(['common' => ['algorithm' => "auto"]]);
			$hasher = $factory->getPasswordHasher('common');
			$finalPWD = $hasher->hash($password);
		}

        $this->password = $finalPWD;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function isIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(\DateTimeImmutable $deleted_at): static
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * @return Collection<int, Recipe>
     */
    public function getRecipes(): Collection
    {
        return $this->recipes;
    }

    public function addRecipe(Recipe $recipe): static
    {
        if (!$this->recipes->contains($recipe)) {
            $this->recipes->add($recipe);
            $recipe->setIdUser($this);
        }

        return $this;
    }

    public function removeRecipe(Recipe $recipe): static
    {
        if ($this->recipes->removeElement($recipe)) {
            // set the owning side to null (unless already changed)
            if ($recipe->getIdUser() === $this) {
                $recipe->setIdUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    /**
     * @return Collection<int, Recipe>
     */
    public function getFavoriteRecipes(): Collection
    {
        return $this->favoriteRecipes;
    }

    public function addFavoriteRecipe(Recipe $favoriteRecipe): static
    {
        //if (!$this->favoriteRecipes->contains($favoriteRecipe)) {
        $this->favoriteRecipes->add($favoriteRecipe);
        //}


        return $this;
    }

    public function removeFavoriteRecipe(Recipe $favoriteRecipe): static
    {
        $this->favoriteRecipes->removeElement($favoriteRecipe);

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use App\Entity\User;
use App\Entity\Ustensil;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
				"label" => "Title",
				"attr" => [
					"class" => "target-input",
				],
				"required" => true,
			])
            ->add('description', TextareaType::class, [
				"label" => "Description",
				"attr" => [
					"class" => "target-input",
				],
				"required" => false,
			])
            ->add('prep_time', NumberType::class, [
				"label" => "Preparation time",
				"attr" => [
					"class" => "target-input",
				],
				"required" => true,
			])
            ->add('cook_time', NumberType::class, [
				"label" => "Cooking time",
				"attr" => [
					"class" => "target-input",
				],
				"required" => true,
			])
            ->add('thumbnail', FileType::class, [
				"label" => "Photo",
				"required" => false,
				'mapped' => false,
				'constraints' => [
					new File([
						'maxSize' => '4096k',
						'mimeTypes' => [
							'image/gif',
							'image/jpeg',
							'image/png',
							'image/webp',
						],
						'mimeTypesMessage' => 'Please select a valid image (.png, .jpg, .jpeg or .webp) and bellow 4Mb',
					])
				],
			])
			->add('instructions', CollectionType::class, [
				"entry_type" => InstructionType::class,
				'entry_options' => [
					"required" => false,
				],
				'prototype' => true,
				"allow_add" => true,
				'by_reference' => false,
			])
			->add('recipeIngredients', CollectionType::class, [
				"entry_type" => IngredientType::class,
				'entry_options' => [
					"required" => false,
				],
				'prototype' => true,
				"allow_add" => true,
				'by_reference' => false,
				"mapped" => false,
			])
			->add('ustensils', null, [
				'choice_label' => 'nom',
				'multiple' => true,
				'expanded' => true,
			])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

templates/recipes/create.twig
{% extends "base.twig" %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('build/recipe_new_css.css') }}">
{% endblock %}

{% block title %} Create an awesome recipe {% endblock %}

{% block body %}
	<main class="container container-full container-translate">
		{{ form_start(form) }}
		<div class="title-send">
			<h1>New recipe</h1>

			<button type="submit" class="btn btn-large">Send</button>
		</div>

		{% if errors is not null %}
			{{ errors }}
		{% endif %}

		{{ form_errors(form) }}

		<section id="top">
			<div class="thumbnail-input">
				<img id="thumbnail-preview" class="target-thumbnail notOK">

				<div id="thumbnail-real-input" class="hidden">
					{{ form_widget(form.thumbnail) }}
				</div>
			</div>

			<div class="title-input single-input">
				<label>{{ form.title.vars.label }}</label>
				{{ form_widget(form.title) }}
			</div>

			<div class="desc-input single-input">
				<label>{{ form.description.vars.label }}</label>
				{{ form_widget(form.description) }}
			</div>
		</section>

		<hr/>

		<section id="timings">
			<div class="timing-input single-input">
				<span class="iconify" data-icon="mingcute:time-fill"></span>
				<label>{{ form.prep_time.vars.label }} (minutes)</label>
				{{ form_widget(form.prep_time) }}
			</div>

			<hr class="vertical">

			<div class="timing-input single-input">
				<span class="iconify" data-icon="mdi:fire"></span>
				<label>{{ form.cook_time.vars.label }} (minutes)</label>
				{{ form_widget(form.cook_time) }}
			</div>
		</section>

		<hr/>

		<section id="ustensils">
			<h3>Ustensils</h3>
			<div class="list-ustensils">
				{{ form_widget(form.ustensils) }}
			</div>
		</section>

		<hr/>

		<section id="ingredients-container">
			<div class="title-btn">
				<h3>Ingredients</h3>

				<div class="ingredient-add">
					<button type="button" class="add_item_link btn btn-large" data-collection-holder-class="ingredients">
						<span class="iconify" data-icon="ic:outline-add-box"></span>
						Add ingredient
					</button>
				</div>
			</div>

			<div
				data-index="{{ form.recipeIngredients|length > 0 ? form.recipeIngredients|last.vars.name + 1 : 0 }}"
				data-prototype="{{ form_widget(form.recipeIngredients.vars.prototype)|e('html_attr') }}"
				class="ingredients"
				id="ingredients"
			>
				{% for it in form.recipeIngredients %}
					<div>
						<div id>
							<div>
								{{ form_row(it.ingredient) }}
							</div>
							<div>
								{{ form_row(it.quantity) }}
							</div>
							<div>
								{{ form_row(it.unit) }}
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</section>

		<hr/>

		<section id="instructions-container">
			<div
				data-index="{{ form.instructions|length > 0 ? form.instructions|last.vars.name + 1 : 0 }}"
				data-prototype="{{ form_widget(form.instructions.vars.prototype)|e('html_attr') }}"
				class="instructions"
				id="instructions"
			>
				{% for it in form.instructions %}
					{{ form_widget(it.mediaFile) }}
					{{ form_widget(it.content) }}
				{% endfor %}
			</div>

			<div class="instruction-add-container">
				<button type="button" class="add_item_link btn btn-large" data-collection-holder-class="instructions">
					<span class="iconify" data-icon="ci:list-add"></span>
					Add instruction
				</button>
			</div>
		</section>

		{{ form_row(form._token) }}

		{{ form_end(form, {'render_rest': false}) }}
	</main>

	<span id="__last-ID__" style="display: none; opacity: 0">0</span>
{% endblock %}

{% block javascripts %}
	{{ encore_entry_script_tags('recipe_new') }}
{% endblock %}

templates/recipes/index.twig
{% extends "base.twig"%}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('build/recipes_index.css') }}">
{% endblock %}

{% block title %} All recipes {% endblock %}

{% block body %}

	{% set can_create_recipes = is_granted('ROLE_USER') or is_granted('ROLE_ADMIN') %}

	<main class="container container-full container-translate">
		<div class="title-container">
			<h1>Recipes available</h1>

			{% if(can_create_recipes) %}
				<a class="btn btn-large" href="{{ path('app_recipes_create') }}">New recipe</a>
			{% endif %}
		</div>

		<section id="filters">
			<div data-filter-trigger class="filters-title chip big-chip undeployed">
				<h2 class="prevent">Filters</h2>
				<span class="iconify" data-icon="mdi:filter"></span>
			</div>

			<div data-filters class="hidden">
				{% include "recipes/filters.twig" %}
			</div>

		</section>

		<section id="results">
			<h2>Results</h2>

			<div class="grid-container">
				{% if recipes|length == 0 %}
					<h4>no recipe.</h4>

					{% if(can_create_recipes) %}
						<a class="btn btn-large" href="{{ path('app_recipes_create') }}">New recipe</a>
					{% endif %}
				{% else %}

				<div class="grid-results">
					{% include "recipes/list.twig" %}
				</div>
				{% endif %}
			</div>
		</section>
	</main>
{% endblock %}

{% block javascripts %}
	<script src="{{ asset('build/recipe_index_js.js') }}"></script>
{% endblock %}

templates/recipes/list.twig
{% for recipe in recipes %}
	<a class="card" href="{{ path('app_recipes_single', {'id': recipe.id}) }}">
		{% if recipe.thumbnail is not null %}
			<img class="recipe-img" src="{{ asset('uploads/recipes/' ~ recipe.thumbnail) }}" alt="recipe image">
		{% endif %}

		<div class="article-container">
			<p><b>{{ recipe.title }}</b></p>
			<p><i>{{ recipe.description }}</i></p>

			<hr/>

			<div class="cook-prep-container">
				<div title="Preparation time" class="prep-time">
					<span class="iconify" data-icon="mingcute:time-fill"></span>
					<p class="target-prep-time">{{ recipe.prepTime ?? 0 }} minute(s)</p>
				</div>

				<div title="Cooking time" class="cook-time">
					<span class="iconify" data-icon="mdi:fire"></span>
					<p class="target-prep-time">{{ recipe.cookTime ?? 0 }} minute(s)</p>
				</div>
			</div>
		</div>
	</a>
{% endfor %}

templates/recipes/single.twig
{% extends "base.twig" %}

{% block opg %}
	{{ parent() }}

	{% if recipe.title %}
		<meta property="og:title" content="{{ recipe.title }}" />
	{% endif %}


	{% if recipe.thumbnail %}
		<meta property="og:image" content='{{ app.request.getSchemeAndHttpHost() ~ "/uploads/recipes/" ~ recipe.thumbnail}}' />
	{% endif %}

	<meta property="og:type" content="article" />

	{% if recipe.description %}
		<meta property="og:description" content="{{ recipe.description }}" />
	{% endif %}

	<meta property="og:determiner" content="auto" />
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('build/recipe_single_css.css') }}">
{% endblock %}

{% block title %}
	{{ recipe.title ?? recipe.description ?? ("Recipe by " ~ author.userIdentifier) }}
{% endblock %}

{% block body %}
	<main class="container-translate">
		<div class="container">
			{% if recipe.thumbnail and recipe.thumbnail is not null %}
				<section id="thumbnail">
					{% include "common/mediaDisplay.twig" with { file: recipe.thumbnail, attrs: {"class": "main-thumbnail"} } %}
				</section>
			{% endif %}

			<div class="content">
				<section id="g-infos">
					<h1>{{ recipe.title }}</h1>
					<p class="description"><i>{{ recipe.description }}</i></p>

					<div class="timings-share">
						<div class="timings">
							<p class="prep">
								<span class="iconify" data-icon="mingcute:time-fill"></span>
								<span class="title-timing">Preparation time</span>
								<span class="val-timing">{{ recipe.prepTime }} min(s)</span>
							</p>
							<p class="cook">
								<span class="iconify" data-icon="mdi:fire"></span>
								<span class="title-timing">Cooking time</span>
								<span class="val-timing">{{ recipe.cookTime }} min(s)</span>
							</p>
						</div>

						<hr class="vertical"/>

						<div class="share">
							<h5>Like</h5>

							<div class="fav">
								{% set nbrLikes = likes ?? 0 %}

								{% if favorite is null %}
									<div class="fav-action">
										<span class="iconify icon-heart" data-icon="mdi:heart"></span> <p class="nbr-likes">{{ nbrLikes }} like{{ nbrLikes > 1 ? 's' : '' }}</p>
									</div>

									Please <a href="{{ path('app_login') }}">login</a> to add this to your favorites.
								{% else %}
									{% if favorite=='true' %}
										<div class="fav-action">
											<a class="fav-link" href="{{ path('app_recipes_favorite', {'id': recipe.id}) }}">
												<span class="iconify icon-heart" data-icon="mdi:heart"></span>
											</a>

											<p class="nbr-likes">{{ nbrLikes }} like{{ nbrLikes > 1 ? 's' : '' }}</p>
										</div>
									{% else %}
										<div class="fav-action">
											<a class="fav-link" href="{{ path('app_recipes_favorite', {'id': recipe.id}) }}">
												<span class="iconify icon-heart" data-icon="mdi:heart-outline"></span>
											</a>

											<p class="nbr-likes">{{ nbrLikes }} like{{ nbrLikes > 1 ? 's' : '' }}</p>
										</div>
									{% endif %}
								{% endif %}

								<div class="user-profile">
									<p>Recipe by
										<a href="{{ path('app_user', {'id': author.id}) }}">
											{{ author.userIdentifier }}
										</a>
									</p>
								</div>
							</div>


							<h5>Share</h5>
							{% include "common/share.twig" %}
						</div>
					</div>
				</section>

				<hr style="margin-top: 2rem !important;margin-bottom: -5px;">

				<section id="needs">
					<div class="ingredients need-container">
						{% if recipe.recipeIngredients|length > 0 %}
							<h5 class="cat-title">
								{{ recipe.recipeIngredients|length }}
								ingredient{{ recipe.recipeIngredients|length > 1 ? 's' : '' }}
							</h5>

							<ul class="cat-container">
								{% for recipeIngre in recipe.recipeIngredients %}
									<li>
										{{ recipeIngre.quantity }}
										{{ recipeIngre.unit }}
										{{ recipeIngre.ingredient.nom }}
									</li>
								{% endfor %}
							</ul>
						{% else %}
							<h5 class="cat-title">No ingredients are needed for this recipe.</h5>
						{% endif %}
					</div>

					<hr class="vertical"/>

					<div class="ustensils need-container">
						{% if recipe.ustensils|length > 0 %}
							<h5 class="cat-title">
								{{ recipe.ustensils|length }}
								ustensil{{ recipe.ustensils|length > 1 ? 's' : '' }}
							</h5>

							<ul class="cat-container">
								{% for ustensil in recipe.ustensils %}
									<li>{{ ustensil.nom }}</li>
								{% endfor %}
							</ul>
						{% else %}
							<h5 class="cat-title">No ustensils are needed for this recipe.</h5>
						{% endif %}
					</div>
				</section>

				<hr>

				<section id="instructions">
					{% if recipe.instructions|length > 0 %}
						{% set index = 0 %}
						{% for instruction in recipe.instructions %}
							<div class="instruction-container">
								<div class="step-separator">
									<h3 class="target-step">
										{% if index+1 < 10 %}
											0{{ index+1 }}
										{% else %}
											{{ index+1 }}
										{% endif %}

									</h3>
								</div>

								<div class="instruction-content">
									{% if instruction.media is not null %}
										{% include "common/mediaDisplay.twig"
										with {
											file: instruction.media,
											attr: {
												"class": "target-media",
												"controls": "true",
											}
										} %}
									{% endif %}

									<div class="instruction-text">
										{{ instruction.content }}
									</div>
								</div>
							</div>

							{%  set index = index+1 %}
						{% endfor %}
					{% else %}
						<h2 class="inst-title">No instructions.</h2>
					{% endif %}
				</section>
			</div>
		</div>
	</main>
{% endblock %}

{% block javascripts %}
	{{ encore_entry_script_tags('recipe_single_js') }}
{% endblock %}